<a href="https://colab.research.google.com/github/estalin01158/Artificialinteligencia/blob/main/Copia_de_Copia_de_trabajo2_2Julios.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a=np.random.randint(1,10,(3,4))
print(a)
tmp=np.mean(a)
print(tmp)
print(a.mean())
tmp=a.mean(axis=1)
print(tmp)
tmp=a.mean(axis=0)
print(tmp)

aux=a.sum()
print(aux)
medianValue=np.median(a,axis=1)
print(medianValue)



[[1 5 4 5]
 [1 6 9 4]
 [6 2 2 9]]
4.5
4.5
[3.75 5.   4.75]
[2.66666667 4.33333333 5.         6.        ]
54
[4.5 5.  4. ]


In [ ]:
#sportin
b=np.random.rand(10)
print(b)
print(b.shape)
b.sort()
print(b)
print(b.shape)
b.sort()
print(b)


[0.4575919  0.65299663 0.78123893 0.83877828 0.29481902 0.6658272
 0.28773364 0.36414764 0.23850979 0.49530506]
(10,)
[0.23850979 0.28773364 0.29481902 0.36414764 0.4575919  0.49530506
 0.65299663 0.6658272  0.78123893 0.83877828]
(10,)
[0.23850979 0.28773364 0.29481902 0.36414764 0.4575919  0.49530506
 0.65299663 0.6658272  0.78123893 0.83877828]


In [ ]:
c=np.array([2,3,4,2,5,3,5])
print(np.unique(c))

[2 3 4 5]


In [ ]:
string1=np.array=(['desk','chair','bulb'])
string2=np.array=(['lamp','bulb','chair'])
tmp1=np.intersect1d(string1,string2)
print(tmp1)
tmp2=np.union1d(string1,string2)
print(tmp2)
tmp3=np.setdiff1d(string1,string2)
print(tmp3)
tmp4=np.in1d(string1,string2)
print(tmp4)

['bulb' 'chair']
['bulb' 'chair' 'desk' 'lamp']
['desk']
[False  True  True]


In [ ]:
#BROADCAST
import numpy as np
aux=np.zeros((4,3))
print(aux)
replicate=np.array([1,2,1])
aux=aux+replicate
print(aux)
replicateCol=np.array([10,10,10])
print(replicateCol.shape)
replicateCol=np.reshape(replicateCol,(3,1))
print(replicateCol.shape)
aux=np.zeros([3,3])
aux1=replicateCol+aux
print(aux1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 2. 1.]
 [1. 2. 1.]
 [1. 2. 1.]
 [1. 2. 1.]]
(3,)
(3, 1)
[[10. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]]
